### ISSUE TITLE
本地部署正常，部署到gitpages后主题丢失

### ISSUE THREAD

**Issue by ranbi666** [shen-yu/hexo-theme-ayer#174]
错误Log如图
![Uploading 错误log.png…]()

**Comment by ranbi666** [comment]
Failed to load resource: net::ERR_TUNNEL_CONNECTION_FAILED
jquery-3.6.0.min.js:1 Uncaught SyntaxError: Unexpected token '<'
lazyload.min.js:1 Uncaught SyntaxError: Unexpected token '<'
jquery.modal.min.js:5 Uncaught ReferenceError: jQuery is not defined
    at jquery.modal.min.js:5:110
    at jquery.modal.min.js:5:134
jquery.justifiedGallery.min.js:8 Uncaught ReferenceError: jQuery is not defined
    at jquery.justifiedGallery.min.js:8:241
    at jquery.justifiedGallery.min.js:8:249
main.js:1 Uncaught SyntaxError: Unexpected token '<'
busuanzi-2.3.pure.min.js:1 Uncaught SyntaxError: Unexpected token '<'
（索引）:460 Uncaught ReferenceError: $ is not defined
    at initCopyCode (（索引）:460:7)
    at （索引）:499:5
    at （索引）:500:4

**Comment by ranbi666** [comment]
![错误log](https://github.com/shen-yu/hexo-theme-ayer/assets/117438943/82929cb9-9d0b-4ee9-b10c-bffa300d0c98)
